# Markdown

**今日の目標**

- Markdownを使った文書を作成できるようになる！


## Markdown とは

Markdown（マークダウン）は、文書を作成するために使われる軽量マークアップ言語の1つである。最もよく知られたマークアップ言語として、ウェブサイトなどの作成に使われるHTML (HyperText Markup Language) があるが、HTMLは（難しくはないが）自力で書くのはやや面倒である。面倒なMark***up***をより簡単にしようというのがMarkd***down***である。

例えば、ここに高知工科大学の公式サイトへのリンクを貼ることにしよう。
HTMLを使うと、「aタグ」と呼ばれるものを使って次のように書くことができる。
```html
<a href="https://www.kochi-tech.ac.jp/" target="_blank">高知工科大学</a>
```

それに対し、Markdownでは、
```markdown
[高知工科大学](https://www.kochi-tech.ac.jp/)
```
と書くことができる。実際のリンクは [高知工科大学](https://www.kochi-tech.ac.jp/) のようになる。

Microsoft Word と異なり、Markdown で書いた文書はテキストファイルとして保存され、VS Code などのテキストエディタで編集できるのでファイルの受け渡しにも便利（相手がWordを持っていなくてもOK）である。

ファイルの編集が完了し、文書として提出・公開するときは、Markdown からHTMLやPDF（あるいはWord）の文書に変換する。この文書（いま皆さんが読んでいるコレ！）は、Markdownを使って書いたファイルからHTMLに変換されてウェブ上に公開されたものである。

今後、コンピュータを使って簡単な文書を作成する際には Markdown を使う習慣を付けると良いだろう。Markdownを使いこなせるようになると、

- レポートの作成
- プレゼンテーション用のスライドの作成
- 卒業論文の執筆（卒論の執筆に使うのは、R Markdown あるいは Quarto Markdown というMarkdown ベースの文書）

などができるようになる。


## 練習

### Markdown ファイルの準備

Markdownを使った文書を作ってみよう。

まず、ターミナルを使ってホームディレクトリに`seminar1`という名前のディレクトリを作る（既に同じ名前のディレクトリがあるなら、これは実行しなくてよい）。
```default
$ mkdir ~/seminar1
```

次に、`seminar1` ディレクトリに移動して、ディレクトリ内に練習用のMarkdownファイルを作ろう。Markdownファイルの拡張子は `.md` である。
```default
$ cd ~/seminar1
$ touch exercise4.md
```

新たに作った空のMarkdownファイルをVS Code で開く。
```default
$ code exercise4.md
```
以降の作業はVS Code 上で行う。

### Markdown を使ってみよう

[Markdown文法の基本](https://www.jaysong.net/RBook/rmarkdown.html#sec-rmarkdown_grammar) を参考に、構造化された文書を作ってみよう！

- 見出しを作る
- 段落を作る
- 箇条書き
  - 番号なしの箇条書き
  - 番号付きの箇条書き
- 文字の強調
- リンクを貼る
- 表の作成
- 画像の挿入



## 第4回の課題

[課題1（小林先生に提出した課題）](https://kut-econ.github.io/math_seminar1/ch1.html)を、Markdownを利用して綺麗な文書に整理し直して提出しなさい。その際、以下の5つの条件を満たすように文書を作成すること。

1. 文書のタイトル（第1レベルの見出し）は「数理セミナーI：課題4」にする（カギカッコは不要）
2. タイトルの下に、氏名、学籍番号、文書の作成日を記す。
3. 各項目（1, 2, 3）に第2レベルの見出し（節タイトル）を付ける
4. 項目1は、箇条書きに変更する。
5. 項目2と項目3については、強調したい部分を**太字**にする。




- 提出期限：**2025年11月<s>16日（土）</s> 26日（水）正午**（日本時間）
- 提出方法：ファイルをメールに添付して担当教員に送信する
  - メールの題名：「数理セミナー1の課題4」
  - 提出するファイルは以下の2つ（以下のファイル名の**StudentID の部分は自分の学籍番号に置き換えること**。例：`kadai4_1290999.md`）
    - `kadai4_StudentID.md`
    - `kadai4_StudentID.pdf`

    

:::{.callout-note}
## 注意：メールの書き方について
メールを送信する前に、以下のリンク先でメールの書き方を確認してください。

- [https://www.rikkyo.ac.jp/about/activities/fd/cdshe/mknpps000001ri7e-att/MoW_10.pdf](https://www.rikkyo.ac.jp/about/activities/fd/cdshe/mknpps000001ri7e-att/MoW_10.pdf)
- [http://www2.ipcku.kansai-u.ac.jp/~iwamoto/email.pdf](http://www2.ipcku.kansai-u.ac.jp/~iwamoto/email.pdf)
- [https://user.keio.ac.jp/~matsuoka/mailsample.htm](https://user.keio.ac.jp/~matsuoka/mailsample.htm)
:::


