# Overleafの使い方

今日の目標

- 数式を含むMarkdownファイルをPDFに変換する方法を覚える
- Overleaf で LaTeX文書を作成する方法を身につける

## Markdown からPDFへの変換

LaTeX 記法の数式を含むMarkdownファイルは、**[Pandoc](https://pandoc-doc-ja.readthedocs.io/ja/latest/users-guide.html)**（と LuaLaTeX）を使ってPDFに変換することができる。

実習のため、課題5（あるいは前回の実習）で作成したMarkdownファイルの内容をPDFに変換してみよう。

まず、前回作成したファイル（ここでは、`kadai5_1270xxx.md` としているが、各自のファイル名に置き換えること）をコピーして、`eg_lec06.md` というファイルを新たに作成し、それをVS Code で開こう。そのために、ターミナル（端末）で以下を実行する。
```default
$ cd ~/seminar1
$ cp kadai5_1270xxx.md eg_lec06.md
$ code eg_lec06.md
```

これをPDFに変換する前に、少し工夫しよう。
PDFにタイトル（およびサブタイトル）と、著者名 (author)、作成日 (date) を表示するために、
ファイルの**最上部に**以下の情報を書き足す。ただし、`author` には自分の氏名と学籍番号を書くこと。

```markdown
---
title: "数理マネジメントセミナーⅠ"
subtitle: "課題5b"
author: "矢内 勇生（1270xxx）"
date: "2023年12月11日"
---
```

ここで書いた、`---` （ハイフン3つで1組）で囲まれた部分を**YAMLヘッダ**という。YAMLとは、"YAML Ain't Markup Language" （YAMLはマークアップ言語ではない）のことであり、ファイルの情報（や構造）を指定するために使う。これをファイルの最上部、すなわちヘッダ (header) に置くのでYAMLヘッダと呼ばれる。

YAMLヘッダの書き方について注意すべき点を以下に挙げる。

- ヘッダの開始（最初の、`---` ）は、必ずファイルの1行目冒頭におく（改行やスペースを入れない）
- ヘッダに記入する各項目の名前（title, subtibleなど）は、半角で記入し、その後に**スペース無しで**半角のコロン `:` を入力する
- コロン `:` の直後に**半角スペースを1つ**（以上）入れる
- 各項目の内容は、**半角の引用符** `"` で囲む
- 項目は1行に1つ
- YAMLヘッダ内に空行（何も記入していない行）を残さない
- ヘッダは `---` で必ず閉じる


タイトルと氏名はヘッダに書いたので、元々のファイルに書いてあったタイトル、氏名、日付等は削除してもよい。ここまでできたら、ファイルを保存する。

次に、この Markdown ファイルをPDFをに変換するために、ターミナル（端末）で以下のコードを実行する。ただし、`eg_lec06.md` は上で編集したファイルのことなので、ファイル名が異なる場合は適宜変更する。同様に、`eg_lec06.pdf` はこれから作成するファイル名なので、他の名前を付けたい場合は変更する。途中のスペース、記号、大文字と小文字の区別などに注意しながら入力しよう。

```default
$ pandoc eg_lec06.md -o eg_lec06.pdf --pdf-engine=lualatex -V documentclass=ltjsarticle
```

うまくいけば、現在の作業ディレクトリにPDFファイルができる。確認してみよう。
すべてのファイルを表示するなら、
```default
$ ls
```
とすればよいが、PDF（ファイル名拡張子が `.pdf` のもの）のみを表示するために、以下のようにする。
```default
$ ls | grep *.pdf
```
上で指定した名前のPDFが見つかれば成功である。


## Overleaf入門

簡単な文書であれば、MarkdownをPDFに変換すれば事足りる。しかし、少し複雑な文書を書きたいとき、Markdownだけでは細かい調整が困難な場合がある。そんなときは、LaTeXを直接使うほうが手っ取り早い。しかし、初心者がLaTeXを使いこなすのはやや難しい。そこで、ウェブブラウザ上でLaTeXを利用することができる、**Overleaf**を使うことにしよう。

### Overleaf のアカウント登録

まず、ウェブブラウザ (Firefox) を起動し、[Overleaf](https://www.overleaf.com/) のサイトを開く。

次に、**無料アカウント**の登録を行う。ページの右上にある "Register" をクリックする。Gmail を利用している者は、"Register using Google" で登録することができる。それ以外の者は、EmailとPasswordを入力し、登録する。登録の確認のためにメールを受け取る必要があるので、すぐに開くことができるメールアドレスを入力すること。また、パスワードは忘れないように！


### Overleaf で日本語文書を作る

登録が完了したら、さっそく Overleaf を使ってみよう。
左上の "New Project" をクリックするといくつか選択肢が提示されるので、"Blank Project" をクリックして新しいプロジェクト（文書）を作成する。プロジェクトに名前を付けるよう促されるので、適当な名前（例：初めてのOverleaf）を入力し、"Create" をクリックする。

プロジェクトできると、画面が縦に3分割されたような表示になる。左の列（おそらく一番幅が狭い）は、ファイル一覧で、最初は `main.tex` というファイルのみが表示されている。真ん中の列（背景が黒い列）がエディタ画面である。ここにファイルの中身が表示されており、ファイルの編集をここで行う。右の列に、ファイルのプレビューが表示されている。最終的にどのようなPDFが出来上がるか、確認することができる。

プレビューを見てみると、登録した名前（アルファベットで入力した場合）や今日の日付（英語）と、プロジェクト名のうちアルファベットで書いた部分が表示されているだろう。日本語は表示されていないはずだ。これには後で対処する。

続いて、エディタに注目しよう。LaTeX文書の中身を見てみると、`\begin{document}` という命令と、`\end{document}` という命令が見つかるだろう。LaTeX記法の数式を勉強したときに見たように、LaTeXでは`\begin{}`と`\end{}`をペアで利用することで、何らかの環境 (environment) を作る。`document` 環境は最も基本的な環境であり、LaTeX文書の中身はこの`document` 環境の中、つまり`\begin{document}` と`\end{document}`の間に書く。

`\begin{document}`よりも上の部分は**プレアンブル** (preamble) と呼ばれ、ここで文書の構造や、追加で利用するパッケージ（数学記号や図の表示など）を指定する。

現時点で日本語が表示できないのは、プレアンブルが適切に設定されていないためである。そこで、プレアンブルを以下の内容に置き換えよう。
```tex
\documentclass[12pt]{ltjsarticle}
\usepackage[ipaex]{luatexja-preset}
\usepackage[margin=1in]{geometry} % 余白の設定
\usepackage{amsmath,amssymb,bm}   % 数学記号を追加
\usepackage{graphicx,color}       % 画像の挿入に必要
\usepackage{setspace}
\doublespacing                    % ダブルスペースにする

\title{数理セミナーI：第6回}
\author{矢内~勇生（1270xxx）}
\date{\today}
```
ただし、`author` の内容は、自分の氏名と学籍番号に置き換えること。


これだけではまだ日本語が正しく表示されない。
左上にあるMenuをクリックして、Compiler を "pdfLaTeX" から "LuaLaTeX" に変更する。
ここまでできたら、プレビュー画面の上にある "Recompile" をクリックしてみよう。
日本語が表示されるはずだ。

### Overleaf で LaTeX

ここからは、`\begin{document}` と`\end{document}`の間に文章を書こう。

通常の日本語文書は普段通り書けばよい。
ただし、文を改行しても、出来上がった文章で改行されるとは限らない。
段落を変えたいときは、1行空けてから文を書けばよい。

節タイトルは、`\section{節タイトル}` で付ける。
同様に、小節は`\subsection{小節タイトル}、小小節は`\subsubsection{小小説}`である。

太字は`\textbf{太字}`で、イタリックは`\textit{italics}`で書ける。
文字に色を付けたいときは、`\textcolor{色}{文字}`とする。例えば、`\textcolor{red}{この文は赤字になる}`のようにする。

LaTeX記法の数式は以前勉強したが、Markdownの場合とやや異なるところがあるので、以下に違いをいくつか示す。

- 文中に数式を入れたいときは `$` と `$` で囲む（これは Markdown と同じ）
- 独立行の数式（数式番号なし）は `\[` と`\]` で囲む（Markdownでは、`$$`と`$$`だった）。たとえば、
```tex
\[
  \bar{x} = \frac{1}{N} \sum_{n=1}^N x_n
\]
```
とする。

- `align` 環境を使うと、番号付きの数式が書ける。たとえば、
```tex
\begin{align}
  \bar{x} = \frac{1}{N} \sum_{n=1}^N x_n
\end{align}
```
とすると、数式に自動的に番号が振られる。

- 数式番号に後で言及したいときは、数式にラベル (label) を付けておくと便利である。たとえば、
```tex
\begin{align}
  \bar{x} = \frac{1}{N} \sum_{n=1}^N x_n \label{mean}
\end{align}
```
とする。この式が (2) だとして、この番号に言及したいときは、「`\eqref{mean}`式より〜」と書くと、「(2) 式より〜」と表示される。つまり、カッコ付きの番号が自動的に挿入される。この書き方を利用すると、数式を追加したり削除したりして数式番号が変わったとしても、LaTeXが自動的に正しい番号を挿入してくれる。

- 数式番号付きで複数行の数式を書きたいときは、次のようにする。
```tex
\begin{align}
  \bar{x} 
  &= \frac{1}{N} \sum_{n=1}^N x_n \\
  &= \frac{1}{N} (x_1 + x_2 + \cdots + x_N)
\end{align}
```
各行に番号が付される。


- 数式番号なしで複数行の数式を書きたいときは、次のようにする。
```tex
\begin{align*}
  \bar{x} 
  &= \frac{1}{N} \sum_{n=1}^N x_n \\
  &= \frac{1}{N} (x_1 + x_2 + \cdots + x_N)
\end{align*}
```

その他の使い方については、[参考文献](#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE)を参照されたい。ウェブ上にも多くの情報があるが、基本的な使い方は[TeX Wiki](https://texwiki.texjp.org/?LaTeX%E5%85%A5%E9%96%80)にまとめられている。


- [Overleafプロジェクトの例](https://www.overleaf.com/read/zzhygsktcbxg#466dd7)


## 第6回の課題


Overleafで以下の問題に対する解答を作成し、解答を記した**PDF**ファイル （拡張子が `.pdf`）を提出しなさい。その際、以下の注意を守ること。

- 文書のタイトルを「数理セミナーI：課題6」にしなさい。
  - `author` に氏名（学籍番号）を記しなさい。
  - `date` に作成日を記しなさい。
- 各問は節タイトルを付けて区別しなさい。
- **提出期限：2023年12月18日（月）午後10時**（日本時間）
- 提出方法：ファイルをメールに添付して担当教員に送信する
  - メールの題名：「数理セミナー1の課題6」
  - 提出するファイル名は `kadai6_StudentID.pdf`
    - ファイル名の**StudentID の部分は自分の学籍番号に置き換えること**（例：`kadai6_1270999.pdf`）
    

### 問1 {-}

[第5回の課題](https://yukiyanai.github.io/mathseminar1/latex.html#%E7%AC%AC5%E5%9B%9E%E3%81%AE%E8%AA%B2%E9%A1%8C) をOverleaf上で実行しなさい（解答を綺麗に整理すること）。


### 問2 {-}

大学入学後に新たに学習した数学の定理から、あなたが素晴らしい（美しい、役に立つ）と思うものを1つ選び、定理の内容を述べた後、その証明を記しなさい（証明を自力で考える必要はない）。最後に、その定理が素晴らしい（美しい、役に立つ）と思う理由を述べなさい。



## 参考文献


- 奥村晴彦、黒木裕介. 2020.『[[改訂第8版] LaTeX 2$\varepsilon$ 美文書作成入門](https://www-opac.lib.kppuc.ac.jp/opac/volume/658924?current=1&q=%E7%BE%8E%E6%96%87%E6%9B%B8&total=7&trans_url=%2Fopac%2Fsearch%3Fcount%3D50%26defaultpage%3D1%26defaulttarget%3Dlocal%26order%3Drecommended_d%26q%3D%25E7%25BE%258E%25E6%2596%2587%25E6%259B%25B8%26search%3D%25E6%25A4%259C%2B%25E7%25B4%25A2%26searchmode%3Dnormal)』技術評論社.
- 奥村晴彦、黒木裕介. 2023.『[改訂第9版] LaTeX 2$\varepsilon$ 美文書作成入門』技術評論社.
- 坂東慶太. 2019.『[インストールいらずのLaTeX入門：Overleafで手軽に文書作成](https://www-opac.lib.kppuc.ac.jp/opac/volume/646682?current=1&q=%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%84%E3%82%89%E3%81%9A%E3%81%AELaTeX%E5%85%A5%E9%96%80&total=1&trans_url=%2Fopac%2Fsearch%3Fcount%3D50%26defaultpage%3D1%26defaulttarget%3Dlocal%26order%3Drecommended_d%26q%3D%25E3%2582%25A4%25E3%2583%25B3%25E3%2582%25B9%25E3%2583%2588%25E3%2583%25BC%25E3%2583%25AB%25E3%2581%2584%25E3%2582%2589%25E3%2581%259A%25E3%2581%25AELaTeX%25E5%2585%25A5%25E9%2596%2580%26search%3D%25E6%25A4%259C%2B%25E7%25B4%25A2%26searchmode%3Dnormal)』東京図書.

